# dane
print("Podaj swoje imie :")
name = input()
print("Podaj swoje nazwisko :")
surname = input()
print("Podaj swoj wiek :")
age = input()
print("Podaj swoja plec :")
sex = input ()
print("Wiec nazywasz sie :")
print(name,surname)
print("wiek to: ",age)
print("I jestes",sex)
print("Dziekuje za wspolprace")
#okej